version: '2'

networks:
  zookeeper_test:

services:
  kafka_1:
    extends:
      file: kafka-base.yaml
      service: kafka_base
    container_name: kfk1.example.com

  kafka_2:
    extends:
      file: kafka-base.yaml
      service: kafka_base
    container_name: kfk2.example.com

  kafka_3:
    extends:
      file: kafka-base.yaml
      service: kafka_base
    container_name: kfk3.example.com