version: '2'

networks:
  zookeeper_test:

services:
  kafka_base:
    image: centos:latest
    tty: true
    stdin_open: true
    command: /bin/bash
    working_dir: /var/kafka
    volumes:
      - ../jdk:/var/kafka/jdk
      - ../kafka/bin:/var/kafka/bin
      - ../kafka/libs:/var/kafka/libs
      - ../kafka/config:/var/kafka/config
      - ../disk/kafka:/var/kafka
      - ../kafka/install.sh:/var/kafka/install.sh
      - ../kafka/test:/var/kafka/test
    networks:
      - zookeeper_test
    