version: '2'

networks:
  zookeeper_test:

services:
  mysql:
    container_name: mysql.example.com
    image: centos:latest
    tty: true
    stdin_open: true
    command: /bin/bash
    working_dir: /var/mysql
    volumes:
      - ../disk/mysql:/var/mysql
      - ../resource/mysql/mysql:/var/mysql/mysql
      - ../resource/mysql:/var/mysql/resource
    ports:
      - "3306:3306"
    networks:
      - zookeeper_test